### ISSUE TITLE
Invalid default values for admin settings

### ISSUE THREAD

**Issue by mudrd8mz** [rschrenk/moodle-block_edureportbook#1]
The settings `role_legalguardian` and `role_student` have the following set as their default value:
```
get_config('block_legalguardian', 'role_legalguadian')
```
and 
```
get_config('block_legalguardian', 'role_student')
```
respectively.

Now, when the `block_legalguardian` is not installed, that is set to FALSE which leads to PHP warnings
```
Warning: array_key_exists(): The first argument should be either a string or an integer in /lib/adminlib.php on line 3326

Warning: array_key_exists(): The first argument should be either a string or an integer in /lib/adminlib.php on line 3326
```

Is this a relic of some early development? A reference to another custom plugin? There is no dependency on `block_legalguardian` declared so it should not be used.

**Comment by rschrenk** [comment]
Thank you, this was only a mixup of the plugin-name (block_edureportbook) and the value (role_legalguardian) - is fixed.

**Comment by mudrd8mz** [comment]
I can still see the warnings in the latest version available in the plugins directory - reported as issue #5.
